import { config } from "./app-config.js";

export const state = {
  defaultTextures: [],
  faceTextures: [],
  isLoadingLocal: false,
  selectedDataUrls: [],
  frostedTexture: null,
  textureCache: new Map(),
  nftInventory: [],
  nftSelection: [],
  nftStatus: "idle",
  nftError: null,
  sumFloorEth: 0,
  floorSnapshotAt: null,
  lessTotalSupply: null,
  lessUpdatedAt: null,
  lessSupplyNow: null,
  lessDeltaLast: null,
  lessDeltaMint: null,
  lessDeltaUpdatedAt: null,
  currentCubeTokenId: null,
  mintPriceWei: null,
  tokenMintPriceWei: null,
  bgImage: null,
  bgImageDataUrl: null,
  rotX: -0.35,
  rotY: 0.65,
  rotVelX: 0,
  rotVelY: 0,
  isDragging: false,
  zoom: config.zoom.initial,
  backdrop: null,
  edgePasses: [],
  lastMouse: null,
  pinchStartDist: null,
  pinchStartZoom: null,
  intro: {
    active: false,
    duration: 0,
    startTime: 0,
    zoomStart: 0,
    zoomEnd: 0,
    baseRotX: 0,
    baseRotY: 0,
    holdStart: null,
    tileTextures: null,
    faceTransforms: null,
    paletteCount: 0,
  },
};

if (typeof window !== "undefined" && window.__CUBIXLES_TEST_HOOKS__) {
  window.__CUBIXLES_STATE__ = state;
}
